name = "telenowvoiceai"
client_id = "5aef351a70518eb6484369ba20f78ecc"

application_url = "https://shopify-telenow-ai-app.onrender.com"

embedded = true

[access_scopes]
scopes = "read_orders,write_orders,read_customers,read_checkouts,read_fulfillments"

use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://shopify-telenow-ai-app.onrender.com/auth/callback"
]

[webhooks]
api_version = "2026-07"

[build]
automatically_update_urls_on_dev = true